### ISSUE TITLE
How to extend the listening for the speech

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#2]
- We can set `recognition.continuous = true` to extend the recognition of the speech
- We then can concatenate results of the speech recognition

**Comment by BurningTreeC** [comment]
I have to blame myself - I've already implemented this functionality without discussing it - sorry guys! But discussion is still open

**Comment by flancast90** [comment]
Thanks for taking initiative there! Everything looks good! I will begin JS work on specific commands/languages/etc

**Comment by SonephetR2** [comment]
Still experiencing this as of version 1.0.5-alpha. If I pause for a fraction of a second, I lose speech recognition. I can barely read any JS but could this have to with the recognition engine not rebooting properly if the transcriptCounter isn't at 0??

**Comment by BurningTreeC** [comment]
@SonephetR2 , what operating system and browser are you using to try this? Have you tried this on speech-to-text.finnsoftware.net with the same bad results?

**Comment by BurningTreeC** [comment]
>could this have to with the recognition engine not rebooting properly if the transcriptCounter isn't at 0??

@SonephetR2 this should not be the cause of the problem. the recognition engine doesn't have to reboot if the transcriptCounter insn't at 0

**Comment by flancast90** [comment]
@SonephetR2, I am running Linux Mint 20 Cinnamon without any issues. In fact, I experience quite the opposite! I actually have to stop the transcription now, since it doesn't recognize I am done speaking.

I'm not sure if plugin updates are pushed automatically to each user, or if they must be re-installed. Try re-installing the plugin from speech-to-text.finnsoftware.net via drag-and-drop

**Comment by BurningTreeC** [comment]
@flancast90 we can now actually stop the recognition by `Ok Wiki stop talking` :grin: we can change that

**Comment by BurningTreeC** [comment]
@flancast90 I changed stopping the recognition to `Ok Wiki stop listening`

**Comment by BurningTreeC** [comment]
@flancast90 I believe we can close this issue, since we've already extended the listening

**Comment by BurningTreeC** [comment]
If @SonephetR2 still has the same issue we can reopen

**Comment by SonephetR2** [comment]
Thanks @BurningTreeC and @flancast90. I wanted to be able to retest a bit more before commenting again. I've been mostly testing accessing speech-to-text.finnsoftware.net directly, on Chrome on two Android phones (one running on Android 10, the other on Android 11), as well as on Linux Mint 20.2 on Chromium's latest build. The plugin works on Android but stills stops whenever I pause, while on Mint/Chromium it stops instantaneously and I can't even record a word, which is why I assumed that Chromium was simply unsupported.

**Comment by BurningTreeC** [comment]
Hi @SonephetR2 , no Chromium is supported. It works with Chromium on my Linux machine (Arch).
You could try switching $:/config/speech-to-text/continuous to yes (also possible through the controlpanel) ... that should make it possible to continue talking even if the speech-recognition wants to stop

**Comment by flancast90** [comment]
@SonetphetR2, it is also worth saying to check if the Mic is allowed on the
speech-to-text website. The behavior you’re describing makes it sound like
it’s blocking it.
